### ISSUE TITLE
TaskA

### ISSUE THREAD

**Issue by AntonZamyatin** [AntonZamyatin/bio-python-course#6]
minimum implemented

**Comment by YakutovDmitriy** [comment]
Cool implementation, I like that, but. I tried to do the following:
```bash
python taskA.py
$ cd ..
$ ls
   task1 DIRECTORY
   task1 DIRECTORY
   ...
   taskA DIRECTORY
   README.md FILE
$ cat README.md
   No such file
$ cat taskA.py
   import ...
```

I guess you have a mistake related to current directory. E.g. you have the following implementation of `cat`:
```python
    def cat(self, file_path):
        if not os.path.exists(file_path):
        ...
```
Current directory of shell inner shell (aka `self.current_folder`) can differ from `os.getcwd()`. But you try to find file `file_path` in `cat` from `os.getcwd()`, not `self.current_folder`

I guess commands like `touch`, `head`, etc have the same issue.

Also your idea with `command_list` can be replaces by `self.__getattr__`, you can read about it if you are interested

**Comment by AntonZamyatin** [comment]
It was such a stupid mistake. fixed
`__getattr__` added thanks

**Comment by YakutovDmitriy** [comment]
Good!

Can you list all additional feautures you implemented? I found:

* `-n` argument in `cat` and `tail`
* `clear` command

Some remarks if you want to continue work on this:
* Initial implementation of `ls` (in my template) supported optional argument (path to directory to list). You can add it if you want
* `head` in actual bash works even if you type `bash -n 2 a.txt`, not `bash a.txt -n 2`. This can be done using `argparse` module. It is pretty simple
