### ISSUE TITLE
Exam task for Anton Zamyatin

### ISSUE THREAD

**Issue by YakutovDmitriy** [AntonZamyatin/bio-python-course#7]
#### Main requirements

Your program should never fail.

You are free to implement the task as you want. In particular, if there are some uncertainties, you have to decide what to do.

You are free to add some functionality. Please describe all features you added.

#### Implement application `tic-tac-toe.py` to play [tic-tac-toe](https://en.wikipedia.org/wiki/Tic-tac-toe).

The user of this application is player. He plays tic-tac-toe versus computer player (implemented by you).

You can draw current state of the game using [ASCII art](https://en.wikipedia.org/wiki/ASCII_art).

---

Lifetime of the application can be splitted into several steps:

1. Choose how to play: Xs or Os. You can skip this step if there are some difficulties: the player can play for Xs always.

2. The game. You should draw empty field. There are moves of two types. After each move you should redraw the field to let player know the current state of the game.

    * Move of the player. In this case you should read move of the player (e.g. from stdin) add apply this move to the game. You can use different format of entering the move. For example you can use chess system, e.g. `C2`. In this case cells of the field should be enumerated.

    * Move of the computer. You program should decide how to move. You can do it with simple random or apply some harder algorithms. Also if you have enough time you can add choice of difficulty of computer player.

3. The end. You should draw field after the end of the game and show the result: win, draw or lose. After this you should terminate your application or propose to play again.

4. At any step of the game the player should be able to exit from game. It is preferred that this is not implemented by `Ctrl + C`.

**Comment by AntonZamyatin** [comment]
Hello.
Job is done but this not the end.
Spent a lot of time on design and my AI is stuped and must be improved.
Never again to start exam work at night =)
So work in folder exam.
Intuitive interface (arrows + space/enter + escape(exit)).
If its needed here is description how to install curses library:

> Install wheel package.
> 
> Go to [this repository](http://www.lfd.uci.edu/~gohlke/pythonlibs/).
> 
> Download a package with your python version, in example for python 3.4:
> 
> curses-2.2-cp34-none-win_amd64.whl
> Install it (this command is for windows, in GNU/Linux install like other package)
> 
> `python -m pip install curses-2.2-cp34-none-win32.whl`
> Just include in your python script:
> 
> import curses 
>

**Comment by YakutovDmitriy** [comment]
Hello,

It is pretty cool that you used a special library for game. The only thing I want to mention is that you have some copy-pasted code (for `O`-game and `X`-game).

But everything is good in common, so you got 10 points

**Comment by AntonZamyatin** [comment]
I know that code is bad =( Feel sad about it but I cant do better at night.

**Comment by YakutovDmitriy** [comment]
I can give you an idea of ideal cpu-player. If you are interested, contact me via telegram
